Updates to pipelines from testing

diff --git a/tasks/2a-igc-img-scan-ibm.yaml b/tasks/2a-igc-img-scan-ibm.yaml
--- a/tasks/2a-igc-img-scan-ibm.yaml
+++ b/tasks/2a-igc-img-scan-ibm.yaml
@@ -26,9 +26,6 @@ spec:
     - default: 'docker.io/garagecatalyst/ibmcloud-dev:1.0.10'
       name: tools-image
       type: string
-  results:
-    - name: image-url
-      description: The url of the image to be pushed
   volumes:
     - name: source
       emptyDir: {}
@@ -80,8 +77,6 @@ spec:
       args:
         - '-c'
         - >
-          set -e 
-
           IMAGE_URL=$(params.image-url)
 
           REGISTRY_URL=$(echo $IMAGE_URL | awk -F / '{print $1}')
@@ -95,25 +90,31 @@ spec:
 
             ibmcloud cr namespace-list
 
-            echo ${IMAGE_URL}
+            echo "Getting the VA status of ${IMAGE_URL}"
 
             sleep 2m
 
-            VA_FLAG=$(ibmcloud cr va ${IMAGE_URL} --output json | grep OK)
+            ibmcloud cr va ${IMAGE_URL} --output json > va-result.json
+            VA_STATUS=$(cat va-result.json | jq -r '.[].status')
 
-            echo ${VA_FLAG}
+            echo "VA scan status: ${VA_STATUS}"
 
-            if [[ -n "${VA_FLAG}" ]]; then
+            if [[ "${VA_STATUS}" == "OK" ]]; then
               echo "VA - No Issues in the image"
+            else if [[ $(cat va-result.json | jq -r '.[].vulnerabilities | length') -gt 0 ]]; then
+              echo "VA Failure: $(cat va-result.json | jq -r '.[].vulnerabilities | length') vulnerabilities found in the image"
+              cat va-result.json | jq -r '.[].vulnerabilities'
+              exit 1
+            else if [[ $(cat va-result.json | jq -r '.[].configuration_issues | length') -gt 0 ]]; then
+              echo "VA Warning - $(cat va-result.json | jq -r '.[].configuration_issues | length') configuration issues found in the image"
+              cat va-result.json | jq -r '.[].configuration_issues'
             else
-              echo "VA - Issues in the image"
-              ibmcloud cr va ${IMAGE_URL} --output json
+              echo "VA Warning: non-OK status from Vulnerability Advisor ${VA_STATUS}"
+              cat va-result.json | jq -r '.[]'
             fi
           else
             echo "The image is not stored in the IBM Cloud Image Registry. Skipping Vulnerability Advisor validation"
           fi
-
-          echo -n "${IMAGE_URL}" | tee $(results.image-url.path)
       volumeMounts:
         - name: source
           mountPath: $(params.source-dir)
