Updates gitops step to create app folder if it doesn't exist

diff --git a/tasks/8-gitops.yaml b/tasks/8-gitops.yaml
--- a/tasks/8-gitops.yaml
+++ b/tasks/8-gitops.yaml
@@ -31,6 +31,9 @@ spec:
     - name: tools-image
       type: string
       default: garagecatalyst/ibmcloud-dev:1.0.10
+    - name: helm-url
+      type: string
+      default: ""
   volumes:
     - name: source
       emptyDir: {}
@@ -79,6 +82,18 @@ spec:
         - configMapRef:
             name: gitops-repo
             optional: true
+        - configMapRef:
+            name: artifactory-config
+            optional: true
+        - secretRef:
+            name: artifactory-access
+            optional: true
+        - configMapRef:
+            name: helm-config
+            optional: true
+        - secretRef:
+            name: helm-access
+            optional: true
       command: ["/bin/bash"]
       args:
         - -c
@@ -92,8 +107,8 @@ spec:
           REGISTRY_URL=$(echo $IMAGE_URL | awk -F / '{print $1}')
           REGISTRY_NAMESPACE=$(echo $IMAGE_URL | awk -F / '{print $2}')
           IMAGE_TAG=$(echo $IMAGE_URL | awk -F / '{print $3}')
-          IMAGE_NAME=$(echo IMAGE_TAG | awk -F : '{print $1}')
-          IMAGE_VERSION=$(echo IMAGE_TAG | awk -F : '{print $2}')
+          IMAGE_NAME=$(echo $IMAGE_TAG | awk -F : '{print $1}')
+          IMAGE_VERSION=$(echo $IMAGE_TAG | awk -F : '{print $2}')
 
           if [[ -z "${host}" ]] || [[ -z "${org}" ]] || [[ -z "${repo}" ]]; then
               echo "GitOps repo has not been configured. Skipping trigger step"
@@ -119,22 +134,45 @@ spec:
           git clone -b ${branch} ${GIT_URL} gitops_cd
           cd gitops_cd
 
-          echo "Requirements before update"
-          cat "./${IMAGE_NAME}/requirements.yaml"
+          if [[ -d "${IMAGE_NAME}" ]]; then
+            echo "Requirements before update"
+            cat "./${IMAGE_NAME}/requirements.yaml"
 
-          # TODO avoid using igc to use yq
-          npm i -g @garage-catalyst/ibm-garage-cloud-cli
-          igc yq w ./${IMAGE_NAME}/requirements.yaml "dependencies[?(@.name == '${IMAGE_NAME}')].version" ${IMAGE_VERSION} -i
+            # TODO avoid using igc to use yq
+            npm i -g @garage-catalyst/ibm-garage-cloud-cli
+            igc yq w ./${IMAGE_NAME}/requirements.yaml "dependencies[?(@.name == '${IMAGE_NAME}')].version" ${IMAGE_VERSION} -i
 
-          echo "Requirements after update"
-          cat "./${IMAGE_NAME}/requirements.yaml"
+            echo "Requirements after update"
+            cat "./${IMAGE_NAME}/requirements.yaml"
+          elif [[ -n "$(params.helm-url)" ]]; then
+            mkdir "${IMAGE_NAME}"
+
+            echo "apiVersion: v2" | \
+              yq w - version "0.1.0" | \
+              yq w - name "${IMAGE_NAME}" | \
+              yq w - description "Chart to configure ArgoCD with the ${IMAGE_NAME} project and its applications" \
+              > "${IMAGE_NAME}/Chart.yaml"
+
+            echo "dependencies: []" | \
+              yq w - "dependencies[0].name" "${IMAGE_NAME}" | \
+              yq w - "dependencies[0].version" "${IMAGE_VERSION}" | \
+              yq w - "dependencies[0].repository" "$(params.helm-url)" \
+              > "${IMAGE_NAME}/requirements.yaml"
+
+            echo "global: {}" | \
+              yq w - "${IMAGE_NAME}.replicaCount" "1" \
+              > "${IMAGE_NAME}/values.yaml"
+          else
+            echo "GitOps repo configured but unable to update application config"
+            exit 1
+          fi
 
           if [[ $(git status -s | wc -l) -eq 0 ]]; then
             echo "No changes"
             exit 0
           fi
 
-          git add -u
+          git add "${IMAGE_NAME}/"
           git commit -m "Updates ${IMAGE_NAME} to ${IMAGE_VERSION}"
           git push -v
       volumeMounts:
